### ISSUE TITLE
No Types Definitions for This Package?

### ISSUE THREAD

**Issue by tobychidi** [Treblle/treblle-utils#1]
So, I joined the hackathon.

I thought I should try to build a Nitro Plugin to support Nuxt (Vue 3) and Nitro.js and I discovered no types available. 

Yes, I can work without it. If I succeed with the plugin I would love to publish as SDK and maybe contribute types. 🤷🏾‍♂️

**Comment by DominusKelvin** [comment]
Great thinking @tobychidi and thank you for wanting to contribute types.

**Comment by tobychidi** [comment]
I have already started work on SDK support for Nuxt and Nitro. I did run into some issues. Needed to figure out how to hook into every API event in a Nitro middleware and append something to the body of the response. So still on it.

**Comment by DominusKelvin** [comment]
Hey @tobychidi do you still  have any blockers? I just cut a new version of this util that will make this easier for you in terms of types
