### ISSUE TITLE
Update README with installation and usage instructions

### ISSUE THREAD

**Issue by ChukwunonsoFrank** [Treblle/treblle-utils#4]
Hey @DominusKelvin, 

I was wondering if I could touch up on the README.md file a bit and update it with installation and usage instructions. I tried to install the package earlier and I didn't know what to `npm install`. Also had to dig into the package to figure out how to use it. It would be a welcome improvement for people building on JavaScript this upcoming hackathon. What do you think?

**Comment by DominusKelvin** [comment]
That's true. Great idea. Create an issue and a supporting PR and I'll take a look.

Thanks

**Comment by ChukwunonsoFrank** [comment]
Alright. Will do 👍

**Comment by ChukwunonsoFrank** [comment]
Is the develop branch the standard for making contributions or do I need to make my own branch?

**Comment by DominusKelvin** [comment]
Yes PR should be made to the develop branch

**Comment by DominusKelvin** [comment]
Hey @ChukwunonsoFrank I've merged your PR resolving this issue, you may now close it if all looks good to you.

**Comment by ChukwunonsoFrank** [comment]
Sure thing. Thanks for the review.

**Comment by DominusKelvin** [comment]
Also I'm working on a PR that will complete this as document README will be complete if there is types support
